[[language]]
name = "go"
indent = { tab-width = 8, unit = "\t" }

# config = { "formatting.gofumpt" = true }

[[language]]
name = "python"
rulers = [89]
roots = ["setup.py", "setup.cfg", "pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
formatter = { command = "sh", args = ["-c", "black --quiet - | isort --profile black -"] }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 8, unit = "\t" }
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "markdown"
rulers = [81]
language-server = { command = "ltex-ls" }
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md" ] }
auto-format = true

# config = { ltex.language = "pt-BR" }
